// Generated by scripts/build-babylon-runtime.mjs.
import '../assets/vendor/babylon-runtime.5c31912818a4.min.js';

if (!globalThis.BABYLON) {
  throw new Error('Arena Babylon runtime failed to initialize');
}

export default globalThis.BABYLON;
